### ISSUE TITLE
Chinese Dict Mirror Needs a Replacement

### ISSUE THREAD

**Issue by harrynull** [harrynull/Flow.Launcher.Dictionary#16]
https://github.com/harrynull/Flow.Launcher.Dictionary/blob/main/src/DictDownloadManager.cs#L41

This Chinese mirror stops working because coding.net requires user to be logged in before downloading any files. We need to find somewhere else to host that file.

**Comment by harrynull** [comment]
Reported Flow-Launcher/Flow.Launcher#1334

**Comment by taooceros** [comment]
Have you tried fastgit?

**Comment by harrynull** [comment]
> Have you tried fastgit?

I didn't know about it. Is it stable in China?

[https://hub.fastgit.org/skywind3000/ECDICT-ultimate/releases/download/1.0.0/ecdict-ultimate-sqlite.zip](this) does seem to work.

**Comment by taooceros** [comment]
I feel like it is good enough? There isn't anything that is stable in China.

**Comment by tower-town** [comment]
I think the downloaded file is too large, you can consider showing the download address in Flow-Launcher plugins

**Comment by tower-town** [comment]
I think the downloaded file is too large, and you can consider displaying the download address in Flow-Launcher plugins, so that users can choose the download method according to their own network conditions

**Comment by harrynull** [comment]
@tower-town that can be done in a follow-up issue, but we might want to just replace the url for now since it prevents basically everyone in China from installing it.
