### ISSUE TITLE
dict files lost when updating plugin

### ISSUE THREAD

**Issue by jjw24** [harrynull/Flow.Launcher.Dictionary#2]
originally from https://github.com/jjw24/WoxDictionary/issues/5

![image](https://user-images.githubusercontent.com/26427004/106377828-d663ce80-63f3-11eb-8ac4-0ca5e2b27dc2.png)

Due to the files not being kept in UserData location.

Suggestion:
Store dict files in UserDataLocation\Settings\Plugins\Flow.Launcher.Dictionary

**Comment by harrynull** [comment]
I am working on a feature where it can download the database and store it to `%LocalAppData%\Flow.Dictionary\ecdict.db` if needed. I feel weird putting it under Settings and the file seems to be too large to roam. Let me know if you think otherwise.
