### ISSUE TITLE
設定檔相關說明

### ISSUE THREAD

**Issue by linitfor** [harrynull/Flow.Launcher.Dictionary#26]
請問下面設定有沒有相關說明呢?
jump to website when you enter any result

![圖片](https://github.com/harrynull/Flow.Launcher.Dictionary/assets/58168507/517e2bca-942a-4081-bbda-1b7d9a8248e0)

**Comment by harrynull** [comment]
输入一个网址，然后`{0}`会被替换成这个词。
例如 `https://google.com/search?q={0}` 会使用 Google 搜索这个词

The {0} in the URL will be replaced with the word. e.g. `https://google.com/search?q={0}` uses Google to search the word

**Comment by linitfor** [comment]
ok 搞定了! 我把它連結到有道辭典上了!
建議把說明 加入到軟體介面上喔~~
